apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-server
spec:
  selector:
    app: postgresql-server
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-server
spec:
  selector:
    matchLabels:
      app: postgresql-server
  template:
    metadata:
      labels:
        app: postgresql-server
    spec:
      #initContainers:
      #  - name: init-db
      #    image: postgres:latest
      #    env:
      #      - name: POSTGRES_PASSWORD
      #        value: "HDLCrin8*"
      #    command:
      #      [
      #        "sh",
      #        "-c",
      #        "until pg_isready -h postgresql-server; do echo waiting for database; sleep 2; done; psql -h postgresql-server -U postgres -c 'CREATE DATABASE courses_db;'",
      #      ]
      #    ports:
      #      - containerPort: 5432
      containers:
        - name: postgresql-server
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "HDLCrin8*"
            - name: POSTGRES_DATABASE
              value: "courses_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-server-pvolume
              mountPath: /var/lib/postgresql/data
            - name: command-script-volume
              mountPath: /app/prepare_database.sh
              subPath: prepare_database.sh
      volumes:
        - name: postgresql-server-pvolume
          persistentVolumeClaim:
            claimName: postgresql-server-pvc
        - name: command-script-volume
          configMap:
            name: command-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-server-replication
spec:
  selector:
    app: postgresql-server
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-courses-api
spec:
  selector:
    app: nodejs-courses-api
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-courses-api
spec:
  selector:
    matchLabels:
      app: nodejs-courses-api
  template:
    metadata:
      labels:
        app: nodejs-courses-api
    spec:
      containers:
        - name: nodejs-courses-api
          image: jcortizs/nodejs_courses_api
          env:
            - name: POSTGRES_HOST
              value: "postgresql-server"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "HDLCrin8*"
            - name: postgresql-server
              value: "postgresql-server"
            - name: POSTGRES_DATABASE
              value: "courses_db"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-sql-server
spec:
  selector:
    app: ms-sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sql-server
spec:
  selector:
    matchLabels:
      app: ms-sql-server
  template:
    metadata:
      labels:
        app: ms-sql-server
    spec:
      containers:
        - name: ms-sql-server
          image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "HDLCrin8*"
            - name: MSSQL_PID
              value: Express
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-resources-api
spec:
  selector:
    app: dotnet-resources-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-resources-api
spec:
  selector:
    matchLabels:
      app: dotnet-resources-api
  template:
    metadata:
      labels:
        app: dotnet-resources-api
    spec:
      containers:
        - name: dotnet-resources-api
          image: jcortizs/dotnet_resources_api
          env:
            - name: ms-sql-server
              value: "ms-sql-server"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: django-gateway-api
spec:
  selector:
    app: django-gateway-api
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-gateway-api
spec:
  selector:
    matchLabels:
      app: django-gateway-api
  template:
    metadata:
      labels:
        app: django-gateway-api
    spec:
      containers:
        - name: django-gateway-api
          image: jcortizs/django_gateway_api
          ports:
            - containerPort: 80
