apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-kafka
  template:
    metadata:
      labels:
        app: zookeeper-kafka
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
        - name: kafka-broker-1
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 2181
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "localhost:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
#          dependsOn:
#            - name: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-kafka-consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-kafka-consumer
  template:
    metadata:
      labels:
        app: nodejs-kafka-consumer
    spec:
      containers:
        - name: nodejs-kafka-consumer-container
          image: jcortizs/nodejs_kafka_consumer
          ports:
            - containerPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1-service
spec:
  selector:
    app: kafka-broker-1
  ports:
    - name: http
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: port-2181
      protocol: TCP
      port: 2181
      targetPort: 2181
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-kafka-consumer-service
spec:
  selector:
    app: nodejs-kafka-consumer
  ports:
    - name: http
      protocol: TCP
      port: 8050
      targetPort: 8050
    - name: port-9092
      protocol: TCP
      port: 9092
      targetPort: 9092
  type: LoadBalancer
